# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 875)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.outputFormatGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputFormatGroupBox.sizePolicy().hasHeightForWidth())
        self.outputFormatGroupBox.setSizePolicy(sizePolicy)
        self.outputFormatGroupBox.setMinimumSize(QtCore.QSize(422, 64))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputFormatGroupBox.setFont(font)
        self.outputFormatGroupBox.setCheckable(False)
        self.outputFormatGroupBox.setObjectName("outputFormatGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.outputFormatGroupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.outputComboBox = QtWidgets.QComboBox(self.outputFormatGroupBox)
        self.outputComboBox.setEditable(False)
        self.outputComboBox.setObjectName("outputComboBox")
        self.outputComboBox.addItem("")
        self.outputComboBox.addItem("")
        self.outputComboBox.addItem("")
        self.gridLayout_9.addWidget(self.outputComboBox, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.outputFormatGroupBox, 5, 2, 1, 1)
        self.productRankGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productRankGroupBox.sizePolicy().hasHeightForWidth())
        self.productRankGroupBox.setSizePolicy(sizePolicy)
        self.productRankGroupBox.setMinimumSize(QtCore.QSize(422, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.productRankGroupBox.setFont(font)
        self.productRankGroupBox.setObjectName("productRankGroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.productRankGroupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.minimumRankLabel = QtWidgets.QLabel(self.productRankGroupBox)
        self.minimumRankLabel.setObjectName("minimumRankLabel")
        self.gridLayout_7.addWidget(self.minimumRankLabel, 0, 0, 1, 1)
        self.minimumRankSpinBox = QtWidgets.QSpinBox(self.productRankGroupBox)
        self.minimumRankSpinBox.setMinimum(0)
        self.minimumRankSpinBox.setMaximum(1000000000)
        self.minimumRankSpinBox.setObjectName("minimumRankSpinBox")
        self.gridLayout_7.addWidget(self.minimumRankSpinBox, 1, 0, 1, 1)
        self.maximumRankSpinBox = QtWidgets.QSpinBox(self.productRankGroupBox)
        self.maximumRankSpinBox.setMinimum(0)
        self.maximumRankSpinBox.setMaximum(1000000000)
        self.maximumRankSpinBox.setObjectName("maximumRankSpinBox")
        self.gridLayout_7.addWidget(self.maximumRankSpinBox, 1, 1, 1, 1)
        self.maximumRankLabel = QtWidgets.QLabel(self.productRankGroupBox)
        self.maximumRankLabel.setObjectName("maximumRankLabel")
        self.gridLayout_7.addWidget(self.maximumRankLabel, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.productRankGroupBox, 3, 2, 1, 1)
        self.productSubrankGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productSubrankGroupBox.sizePolicy().hasHeightForWidth())
        self.productSubrankGroupBox.setSizePolicy(sizePolicy)
        self.productSubrankGroupBox.setMinimumSize(QtCore.QSize(422, 89))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.productSubrankGroupBox.setFont(font)
        self.productSubrankGroupBox.setObjectName("productSubrankGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.productSubrankGroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.minimumSubrankLabel = QtWidgets.QLabel(self.productSubrankGroupBox)
        self.minimumSubrankLabel.setObjectName("minimumSubrankLabel")
        self.gridLayout_8.addWidget(self.minimumSubrankLabel, 0, 0, 1, 1)
        self.minimumSubrankSpinBox = QtWidgets.QSpinBox(self.productSubrankGroupBox)
        self.minimumSubrankSpinBox.setMaximum(1000000000)
        self.minimumSubrankSpinBox.setObjectName("minimumSubrankSpinBox")
        self.gridLayout_8.addWidget(self.minimumSubrankSpinBox, 1, 0, 1, 1)
        self.maximumSubrankLabel = QtWidgets.QLabel(self.productSubrankGroupBox)
        self.maximumSubrankLabel.setObjectName("maximumSubrankLabel")
        self.gridLayout_8.addWidget(self.maximumSubrankLabel, 0, 2, 1, 1)
        self.maximumSubrankSpinBox = QtWidgets.QSpinBox(self.productSubrankGroupBox)
        self.maximumSubrankSpinBox.setMaximum(1000000000)
        self.maximumSubrankSpinBox.setObjectName("maximumSubrankSpinBox")
        self.gridLayout_8.addWidget(self.maximumSubrankSpinBox, 1, 2, 1, 1)
        self.gridLayout_6.addWidget(self.productSubrankGroupBox, 4, 2, 1, 1)
        self.selectSubcategoryGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSubcategoryGroupBox.sizePolicy().hasHeightForWidth())
        self.selectSubcategoryGroupBox.setSizePolicy(sizePolicy)
        self.selectSubcategoryGroupBox.setMinimumSize(QtCore.QSize(310, 700))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectSubcategoryGroupBox.setFont(font)
        self.selectSubcategoryGroupBox.setTitle("")
        self.selectSubcategoryGroupBox.setObjectName("selectSubcategoryGroupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.selectSubcategoryGroupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.selectAllSubcategoryCheckBox = QtWidgets.QCheckBox(self.selectSubcategoryGroupBox)
        self.selectAllSubcategoryCheckBox.setObjectName("selectAllSubcategoryCheckBox")
        self.gridLayout_11.addWidget(self.selectAllSubcategoryCheckBox, 0, 0, 1, 1)
        self.selectSubcategoryListWidget = QtWidgets.QListWidget(self.selectSubcategoryGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectSubcategoryListWidget.setFont(font)
        self.selectSubcategoryListWidget.setIconSize(QtCore.QSize(24, 24))
        self.selectSubcategoryListWidget.setObjectName("selectSubcategoryListWidget")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/base/backend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectSubcategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectSubcategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectSubcategoryListWidget.addItem(item)
        self.gridLayout_11.addWidget(self.selectSubcategoryListWidget, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.selectSubcategoryGroupBox, 1, 1, 6, 1)
        self.starRatingGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starRatingGroupBox.sizePolicy().hasHeightForWidth())
        self.starRatingGroupBox.setSizePolicy(sizePolicy)
        self.starRatingGroupBox.setMinimumSize(QtCore.QSize(422, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.starRatingGroupBox.setFont(font)
        self.starRatingGroupBox.setObjectName("starRatingGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.starRatingGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.oneStarRadioButton = QtWidgets.QRadioButton(self.starRatingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oneStarRadioButton.setFont(font)
        self.oneStarRadioButton.setObjectName("oneStarRadioButton")
        self.gridLayout_4.addWidget(self.oneStarRadioButton, 0, 0, 1, 1)
        self.fourStarRadioButton = QtWidgets.QRadioButton(self.starRatingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fourStarRadioButton.setFont(font)
        self.fourStarRadioButton.setObjectName("fourStarRadioButton")
        self.gridLayout_4.addWidget(self.fourStarRadioButton, 0, 4, 1, 1)
        self.twoStarRadioButton = QtWidgets.QRadioButton(self.starRatingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.twoStarRadioButton.setFont(font)
        self.twoStarRadioButton.setObjectName("twoStarRadioButton")
        self.gridLayout_4.addWidget(self.twoStarRadioButton, 0, 1, 1, 1)
        self.threeStarRadioButton = QtWidgets.QRadioButton(self.starRatingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threeStarRadioButton.setFont(font)
        self.threeStarRadioButton.setChecked(True)
        self.threeStarRadioButton.setObjectName("threeStarRadioButton")
        self.gridLayout_4.addWidget(self.threeStarRadioButton, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.starRatingGroupBox, 1, 2, 1, 1)
        self.outputDirectoryGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDirectoryGroupBox.sizePolicy().hasHeightForWidth())
        self.outputDirectoryGroupBox.setSizePolicy(sizePolicy)
        self.outputDirectoryGroupBox.setMinimumSize(QtCore.QSize(422, 295))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputDirectoryGroupBox.setFont(font)
        self.outputDirectoryGroupBox.setObjectName("outputDirectoryGroupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.outputDirectoryGroupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.outputDirectoryListWidget = QtWidgets.QListWidget(self.outputDirectoryGroupBox)
        self.outputDirectoryListWidget.setMinimumSize(QtCore.QSize(391, 220))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.outputDirectoryListWidget.setFont(font)
        self.outputDirectoryListWidget.setIconSize(QtCore.QSize(24, 24))
        self.outputDirectoryListWidget.setObjectName("outputDirectoryListWidget")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/base/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.outputDirectoryListWidget.addItem(item)
        self.gridLayout_10.addWidget(self.outputDirectoryListWidget, 1, 0, 1, 2)
        self.outputDirectoryLineEdit = QtWidgets.QLineEdit(self.outputDirectoryGroupBox)
        self.outputDirectoryLineEdit.setMinimumSize(QtCore.QSize(281, 30))
        self.outputDirectoryLineEdit.setObjectName("outputDirectoryLineEdit")
        self.gridLayout_10.addWidget(self.outputDirectoryLineEdit, 0, 0, 1, 1)
        self.outputDirectoryBrowseButton = QtWidgets.QPushButton(self.outputDirectoryGroupBox)
        self.outputDirectoryBrowseButton.setMinimumSize(QtCore.QSize(91, 30))
        self.outputDirectoryBrowseButton.setObjectName("outputDirectoryBrowseButton")
        self.gridLayout_10.addWidget(self.outputDirectoryBrowseButton, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.outputDirectoryGroupBox, 6, 2, 1, 1)
        self.productStatusGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productStatusGroupBox.sizePolicy().hasHeightForWidth())
        self.productStatusGroupBox.setSizePolicy(sizePolicy)
        self.productStatusGroupBox.setMinimumSize(QtCore.QSize(422, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.productStatusGroupBox.setFont(font)
        self.productStatusGroupBox.setObjectName("productStatusGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.productStatusGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.notAvailableProductRadioButton = QtWidgets.QRadioButton(self.productStatusGroupBox)
        self.notAvailableProductRadioButton.setChecked(True)
        self.notAvailableProductRadioButton.setObjectName("notAvailableProductRadioButton")
        self.gridLayout_5.addWidget(self.notAvailableProductRadioButton, 0, 1, 1, 1)
        self.availableProductRadioButton = QtWidgets.QRadioButton(self.productStatusGroupBox)
        self.availableProductRadioButton.setObjectName("availableProductRadioButton")
        self.gridLayout_5.addWidget(self.availableProductRadioButton, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.productStatusGroupBox, 2, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.programStatus = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programStatus.sizePolicy().hasHeightForWidth())
        self.programStatus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.programStatus.setFont(font)
        self.programStatus.setObjectName("programStatus")
        self.gridLayout_2.addWidget(self.programStatus, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 7, 0, 1, 3)
        self.selectCategoryGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.selectCategoryGroupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectCategoryGroupBox.sizePolicy().hasHeightForWidth())
        self.selectCategoryGroupBox.setSizePolicy(sizePolicy)
        self.selectCategoryGroupBox.setMinimumSize(QtCore.QSize(310, 700))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectCategoryGroupBox.setFont(font)
        self.selectCategoryGroupBox.setTitle("")
        self.selectCategoryGroupBox.setFlat(False)
        self.selectCategoryGroupBox.setCheckable(False)
        self.selectCategoryGroupBox.setChecked(False)
        self.selectCategoryGroupBox.setObjectName("selectCategoryGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.selectCategoryGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.selectAllCategoriesCheckBox = QtWidgets.QCheckBox(self.selectCategoryGroupBox)
        self.selectAllCategoriesCheckBox.setChecked(False)
        self.selectAllCategoriesCheckBox.setObjectName("selectAllCategoriesCheckBox")
        self.gridLayout_3.addWidget(self.selectAllCategoriesCheckBox, 0, 0, 1, 1)
        self.categoryRefreshButton = QtWidgets.QPushButton(self.selectCategoryGroupBox)
        self.categoryRefreshButton.setObjectName("categoryRefreshButton")
        self.gridLayout_3.addWidget(self.categoryRefreshButton, 0, 1, 1, 1)
        self.selectCategoryListWidget = QtWidgets.QListWidget(self.selectCategoryGroupBox)
        self.selectCategoryListWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.selectCategoryListWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectCategoryListWidget.setFont(font)
        self.selectCategoryListWidget.setWhatsThis("")
        self.selectCategoryListWidget.setIconSize(QtCore.QSize(24, 24))
        self.selectCategoryListWidget.setObjectName("selectCategoryListWidget")
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/base/grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon2)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon2)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon2)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon2)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        self.gridLayout_3.addWidget(self.selectCategoryListWidget, 1, 0, 1, 2)
        self.gridLayout_6.addWidget(self.selectCategoryGroupBox, 1, 0, 6, 1)
        self.chooseDomainGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseDomainGroupBox.sizePolicy().hasHeightForWidth())
        self.chooseDomainGroupBox.setSizePolicy(sizePolicy)
        self.chooseDomainGroupBox.setMinimumSize(QtCore.QSize(738, 80))
        self.chooseDomainGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chooseDomainGroupBox.setFont(font)
        self.chooseDomainGroupBox.setTitle("")
        self.chooseDomainGroupBox.setObjectName("chooseDomainGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.chooseDomainGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.urlComboBox = QtWidgets.QComboBox(self.chooseDomainGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlComboBox.sizePolicy().hasHeightForWidth())
        self.urlComboBox.setSizePolicy(sizePolicy)
        self.urlComboBox.setMinimumSize(QtCore.QSize(350, 40))
        self.urlComboBox.setEditable(True)
        self.urlComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.urlComboBox.setObjectName("urlComboBox")
        self.urlComboBox.addItem("")
        self.urlComboBox.addItem("")
        self.gridLayout.addWidget(self.urlComboBox, 0, 0, 1, 1)
        self.searchComboBox = QtWidgets.QComboBox(self.chooseDomainGroupBox)
        self.searchComboBox.setMinimumSize(QtCore.QSize(350, 40))
        self.searchComboBox.setEditable(True)
        self.searchComboBox.setObjectName("searchComboBox")
        self.searchComboBox.addItem("")
        self.gridLayout.addWidget(self.searchComboBox, 0, 2, 1, 1)
        self.searchPushButton = QtWidgets.QPushButton(self.chooseDomainGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchPushButton.sizePolicy().hasHeightForWidth())
        self.searchPushButton.setSizePolicy(sizePolicy)
        self.searchPushButton.setMinimumSize(QtCore.QSize(90, 40))
        self.searchPushButton.setObjectName("searchPushButton")
        self.gridLayout.addWidget(self.searchPushButton, 0, 3, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.chooseDomainGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setMinimumSize(QtCore.QSize(90, 40))
        self.connectButton.setAutoFillBackground(False)
        self.connectButton.setStyleSheet("")
        self.connectButton.setIconSize(QtCore.QSize(16, 16))
        self.connectButton.setAutoDefault(False)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.chooseDomainGroupBox, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setAcceptDrops(False)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionAbout_Textract = QtWidgets.QAction(MainWindow)
        self.actionAbout_Textract.setObjectName("actionAbout_Textract")
        self.action_About_Textract = QtWidgets.QAction(MainWindow)
        self.action_About_Textract.setObjectName("action_About_Textract")
        self.action_About_Author = QtWidgets.QAction(MainWindow)
        self.action_About_Author.setObjectName("action_About_Author")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Keetext"))
        self.outputFormatGroupBox.setTitle(_translate("MainWindow", "Output Format"))
        self.outputComboBox.setItemText(0, _translate("MainWindow", "All in One File"))
        self.outputComboBox.setItemText(1, _translate("MainWindow", "Based on Category"))
        self.outputComboBox.setItemText(2, _translate("MainWindow", "Based on Subcategory"))
        self.productRankGroupBox.setTitle(_translate("MainWindow", "Product Rank"))
        self.minimumRankLabel.setText(_translate("MainWindow", "Minimum"))
        self.maximumRankLabel.setText(_translate("MainWindow", "Maximum"))
        self.productSubrankGroupBox.setTitle(_translate("MainWindow", "Product Sub-rank"))
        self.minimumSubrankLabel.setText(_translate("MainWindow", "Minimum"))
        self.maximumSubrankLabel.setText(_translate("MainWindow", "Maximum"))
        self.selectAllSubcategoryCheckBox.setText(_translate("MainWindow", "Select Subcategory"))
        __sortingEnabled = self.selectSubcategoryListWidget.isSortingEnabled()
        self.selectSubcategoryListWidget.setSortingEnabled(False)
        item = self.selectSubcategoryListWidget.item(0)
        item.setText(_translate("MainWindow", "Sample Subcategory 1"))
        item = self.selectSubcategoryListWidget.item(1)
        item.setText(_translate("MainWindow", "Sample Subcategory 2"))
        item = self.selectSubcategoryListWidget.item(2)
        item.setText(_translate("MainWindow", "Sample Subcategory 3"))
        self.selectSubcategoryListWidget.setSortingEnabled(__sortingEnabled)
        self.starRatingGroupBox.setTitle(_translate("MainWindow", "Select Star Rating"))
        self.oneStarRadioButton.setText(_translate("MainWindow", "One Star"))
        self.fourStarRadioButton.setText(_translate("MainWindow", "Four Stars"))
        self.twoStarRadioButton.setText(_translate("MainWindow", "Two Stars"))
        self.threeStarRadioButton.setText(_translate("MainWindow", "Three Stars"))
        self.outputDirectoryGroupBox.setTitle(_translate("MainWindow", "Output Directory"))
        __sortingEnabled = self.outputDirectoryListWidget.isSortingEnabled()
        self.outputDirectoryListWidget.setSortingEnabled(False)
        item = self.outputDirectoryListWidget.item(0)
        item.setText(_translate("MainWindow", "Sample Output File 1"))
        self.outputDirectoryListWidget.setSortingEnabled(__sortingEnabled)
        self.outputDirectoryBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.productStatusGroupBox.setTitle(_translate("MainWindow", "Product Status"))
        self.notAvailableProductRadioButton.setText(_translate("MainWindow", "Not Available Product"))
        self.availableProductRadioButton.setText(_translate("MainWindow", "All Available Product"))
        self.programStatus.setText(_translate("MainWindow", "Ready"))
        self.selectAllCategoriesCheckBox.setText(_translate("MainWindow", "Top Categories"))
        self.categoryRefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.selectCategoryListWidget.setToolTip(_translate("MainWindow", "Select the Categories of Interest"))
        __sortingEnabled = self.selectCategoryListWidget.isSortingEnabled()
        self.selectCategoryListWidget.setSortingEnabled(False)
        item = self.selectCategoryListWidget.item(0)
        item.setText(_translate("MainWindow", "Sample Category 1"))
        item = self.selectCategoryListWidget.item(1)
        item.setText(_translate("MainWindow", "Sample Category 2"))
        item = self.selectCategoryListWidget.item(2)
        item.setText(_translate("MainWindow", "Sample Category 3"))
        item = self.selectCategoryListWidget.item(3)
        item.setText(_translate("MainWindow", "Sample Category 4"))
        item = self.selectCategoryListWidget.item(4)
        item.setText(_translate("MainWindow", "Sample Category 5"))
        self.selectCategoryListWidget.setSortingEnabled(__sortingEnabled)
        self.urlComboBox.setToolTip(_translate("MainWindow", "the feature for changing various Amazon Domains is Coming Soon!"))
        self.urlComboBox.setItemText(0, _translate("MainWindow", "https://www.amazon.de"))
        self.urlComboBox.setItemText(1, _translate("MainWindow", "https://www.amazon.com"))
        self.searchComboBox.setItemText(0, _translate("MainWindow", "Search"))
        self.searchPushButton.setText(_translate("MainWindow", "Search"))
        self.connectButton.setText(_translate("MainWindow", "Start"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.actionAbout_Textract.setText(_translate("MainWindow", "About Textract"))
        self.action_About_Textract.setText(_translate("MainWindow", "&About Textract"))
        self.action_About_Author.setText(_translate("MainWindow", "&About Author"))

# import base_rc
