# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.outputFormatGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputFormatGroupBox.sizePolicy().hasHeightForWidth())
        self.outputFormatGroupBox.setSizePolicy(sizePolicy)
        self.outputFormatGroupBox.setMinimumSize(QtCore.QSize(422, 64))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputFormatGroupBox.setFont(font)
        self.outputFormatGroupBox.setCheckable(False)
        self.outputFormatGroupBox.setObjectName("outputFormatGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.outputFormatGroupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.outputComboBox = QtWidgets.QComboBox(self.outputFormatGroupBox)
        self.outputComboBox.setEditable(False)
        self.outputComboBox.setObjectName("outputComboBox")
        self.outputComboBox.addItem("")
        self.outputComboBox.addItem("")
        self.outputComboBox.addItem("")
        self.gridLayout_9.addWidget(self.outputComboBox, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.outputFormatGroupBox, 5, 2, 1, 1)
        self.starRatingGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starRatingGroupBox.sizePolicy().hasHeightForWidth())
        self.starRatingGroupBox.setSizePolicy(sizePolicy)
        self.starRatingGroupBox.setMinimumSize(QtCore.QSize(422, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.starRatingGroupBox.setFont(font)
        self.starRatingGroupBox.setObjectName("starRatingGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.starRatingGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fiveStarRadioButton = QtWidgets.QRadioButton(self.starRatingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fiveStarRadioButton.setFont(font)
        self.fiveStarRadioButton.setObjectName("fiveStarRadioButton")
        self.gridLayout_4.addWidget(self.fiveStarRadioButton, 1, 0, 2, 1)
        self.twoStarRadioButton = QtWidgets.QRadioButton(self.starRatingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.twoStarRadioButton.setFont(font)
        self.twoStarRadioButton.setObjectName("twoStarRadioButton")
        self.gridLayout_4.addWidget(self.twoStarRadioButton, 0, 1, 1, 1)
        self.oneStarRadioButton = QtWidgets.QRadioButton(self.starRatingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.oneStarRadioButton.setFont(font)
        self.oneStarRadioButton.setObjectName("oneStarRadioButton")
        self.gridLayout_4.addWidget(self.oneStarRadioButton, 0, 0, 1, 1)
        self.fourStarRadioButton = QtWidgets.QRadioButton(self.starRatingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fourStarRadioButton.setFont(font)
        self.fourStarRadioButton.setObjectName("fourStarRadioButton")
        self.gridLayout_4.addWidget(self.fourStarRadioButton, 0, 4, 1, 1)
        self.threeStarRadioButton = QtWidgets.QRadioButton(self.starRatingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threeStarRadioButton.setFont(font)
        self.threeStarRadioButton.setObjectName("threeStarRadioButton")
        self.gridLayout_4.addWidget(self.threeStarRadioButton, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.starRatingGroupBox, 1, 2, 1, 1)
        self.productRankGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productRankGroupBox.sizePolicy().hasHeightForWidth())
        self.productRankGroupBox.setSizePolicy(sizePolicy)
        self.productRankGroupBox.setMinimumSize(QtCore.QSize(422, 89))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.productRankGroupBox.setFont(font)
        self.productRankGroupBox.setObjectName("productRankGroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.productRankGroupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.minimumRankLabel = QtWidgets.QLabel(self.productRankGroupBox)
        self.minimumRankLabel.setObjectName("minimumRankLabel")
        self.gridLayout_7.addWidget(self.minimumRankLabel, 0, 0, 1, 1)
        self.minimumRankSpinBox = QtWidgets.QSpinBox(self.productRankGroupBox)
        self.minimumRankSpinBox.setMinimum(0)
        self.minimumRankSpinBox.setMaximum(1000000000)
        self.minimumRankSpinBox.setObjectName("minimumRankSpinBox")
        self.gridLayout_7.addWidget(self.minimumRankSpinBox, 1, 0, 1, 1)
        self.maximumRankSpinBox = QtWidgets.QSpinBox(self.productRankGroupBox)
        self.maximumRankSpinBox.setMinimum(0)
        self.maximumRankSpinBox.setMaximum(1000000000)
        self.maximumRankSpinBox.setObjectName("maximumRankSpinBox")
        self.gridLayout_7.addWidget(self.maximumRankSpinBox, 1, 1, 1, 1)
        self.maximumRankLabel = QtWidgets.QLabel(self.productRankGroupBox)
        self.maximumRankLabel.setObjectName("maximumRankLabel")
        self.gridLayout_7.addWidget(self.maximumRankLabel, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.productRankGroupBox, 3, 2, 1, 1)
        self.productSubrankGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productSubrankGroupBox.sizePolicy().hasHeightForWidth())
        self.productSubrankGroupBox.setSizePolicy(sizePolicy)
        self.productSubrankGroupBox.setMinimumSize(QtCore.QSize(422, 89))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.productSubrankGroupBox.setFont(font)
        self.productSubrankGroupBox.setObjectName("productSubrankGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.productSubrankGroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.productSubrankGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.productSubrankGroupBox)
        self.spinBox_3.setMaximum(1000000000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_8.addWidget(self.spinBox_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.productSubrankGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 2, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.productSubrankGroupBox)
        self.spinBox_4.setMaximum(1000000000)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_8.addWidget(self.spinBox_4, 1, 2, 1, 1)
        self.gridLayout_6.addWidget(self.productSubrankGroupBox, 4, 2, 1, 1)
        self.productStatusGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productStatusGroupBox.sizePolicy().hasHeightForWidth())
        self.productStatusGroupBox.setSizePolicy(sizePolicy)
        self.productStatusGroupBox.setMinimumSize(QtCore.QSize(422, 62))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.productStatusGroupBox.setFont(font)
        self.productStatusGroupBox.setObjectName("productStatusGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.productStatusGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_7 = QtWidgets.QRadioButton(self.productStatusGroupBox)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_5.addWidget(self.radioButton_7, 0, 1, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.productStatusGroupBox)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_5.addWidget(self.radioButton_6, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.productStatusGroupBox, 2, 2, 1, 1)
        self.outputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputGroupBox.sizePolicy().hasHeightForWidth())
        self.outputGroupBox.setSizePolicy(sizePolicy)
        self.outputGroupBox.setMinimumSize(QtCore.QSize(422, 295))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputGroupBox.setFont(font)
        self.outputGroupBox.setObjectName("outputGroupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.outputGroupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.outputDListWidget = QtWidgets.QListWidget(self.outputGroupBox)
        self.outputDListWidget.setMinimumSize(QtCore.QSize(391, 220))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.outputDListWidget.setFont(font)
        self.outputDListWidget.setIconSize(QtCore.QSize(24, 24))
        self.outputDListWidget.setObjectName("outputDListWidget")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/base/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.outputDListWidget.addItem(item)
        self.gridLayout_10.addWidget(self.outputDListWidget, 1, 0, 1, 2)
        self.outputLineEdit = QtWidgets.QLineEdit(self.outputGroupBox)
        self.outputLineEdit.setMinimumSize(QtCore.QSize(281, 30))
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.gridLayout_10.addWidget(self.outputLineEdit, 0, 0, 1, 1)
        self.outputBrowseButton = QtWidgets.QPushButton(self.outputGroupBox)
        self.outputBrowseButton.setMinimumSize(QtCore.QSize(91, 30))
        self.outputBrowseButton.setObjectName("outputBrowseButton")
        self.gridLayout_10.addWidget(self.outputBrowseButton, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.outputGroupBox, 6, 2, 1, 1)
        self.selectProjectGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.selectProjectGroupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectProjectGroupBox.sizePolicy().hasHeightForWidth())
        self.selectProjectGroupBox.setSizePolicy(sizePolicy)
        self.selectProjectGroupBox.setMinimumSize(QtCore.QSize(310, 806))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectProjectGroupBox.setFont(font)
        self.selectProjectGroupBox.setTitle("")
        self.selectProjectGroupBox.setFlat(False)
        self.selectProjectGroupBox.setCheckable(False)
        self.selectProjectGroupBox.setChecked(False)
        self.selectProjectGroupBox.setObjectName("selectProjectGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.selectProjectGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.topCategoriesCheckBox = QtWidgets.QCheckBox(self.selectProjectGroupBox)
        self.topCategoriesCheckBox.setChecked(False)
        self.topCategoriesCheckBox.setObjectName("topCategoriesCheckBox")
        self.gridLayout_3.addWidget(self.topCategoriesCheckBox, 0, 0, 1, 1)
        self.selectCategoryListWidget = QtWidgets.QListWidget(self.selectProjectGroupBox)
        self.selectCategoryListWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.selectCategoryListWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectCategoryListWidget.setFont(font)
        self.selectCategoryListWidget.setWhatsThis("")
        self.selectCategoryListWidget.setIconSize(QtCore.QSize(24, 24))
        self.selectCategoryListWidget.setObjectName("selectCategoryListWidget")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/base/grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectCategoryListWidget.addItem(item)
        self.gridLayout_3.addWidget(self.selectCategoryListWidget, 1, 0, 1, 2)
        self.gridLayout_6.addWidget(self.selectProjectGroupBox, 0, 0, 7, 1)
        self.selectTableGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectTableGroupBox.sizePolicy().hasHeightForWidth())
        self.selectTableGroupBox.setSizePolicy(sizePolicy)
        self.selectTableGroupBox.setMinimumSize(QtCore.QSize(310, 720))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectTableGroupBox.setFont(font)
        self.selectTableGroupBox.setTitle("")
        self.selectTableGroupBox.setObjectName("selectTableGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.selectTableGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selectSubcategoryCheckBox = QtWidgets.QCheckBox(self.selectTableGroupBox)
        self.selectSubcategoryCheckBox.setObjectName("selectSubcategoryCheckBox")
        self.gridLayout_2.addWidget(self.selectSubcategoryCheckBox, 0, 0, 1, 1)
        self.selectSubcategoryListWidget = QtWidgets.QListWidget(self.selectTableGroupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selectSubcategoryListWidget.setFont(font)
        self.selectSubcategoryListWidget.setIconSize(QtCore.QSize(24, 24))
        self.selectSubcategoryListWidget.setObjectName("selectSubcategoryListWidget")
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/base/backend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectSubcategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon2)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectSubcategoryListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon2)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.selectSubcategoryListWidget.addItem(item)
        self.gridLayout_2.addWidget(self.selectSubcategoryListWidget, 1, 0, 1, 2)
        self.gridLayout_6.addWidget(self.selectTableGroupBox, 1, 1, 6, 1)
        self.openProjectGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openProjectGroupBox.sizePolicy().hasHeightForWidth())
        self.openProjectGroupBox.setSizePolicy(sizePolicy)
        self.openProjectGroupBox.setMinimumSize(QtCore.QSize(738, 80))
        self.openProjectGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openProjectGroupBox.setFont(font)
        self.openProjectGroupBox.setObjectName("openProjectGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.openProjectGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.connectButton = QtWidgets.QPushButton(self.openProjectGroupBox)
        self.connectButton.setMinimumSize(QtCore.QSize(91, 41))
        self.connectButton.setAutoFillBackground(False)
        self.connectButton.setStyleSheet("")
        self.connectButton.setIconSize(QtCore.QSize(64, 32))
        self.connectButton.setAutoDefault(False)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 0, 1, 1, 1)
        self.urlComboBox = QtWidgets.QComboBox(self.openProjectGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlComboBox.sizePolicy().hasHeightForWidth())
        self.urlComboBox.setSizePolicy(sizePolicy)
        self.urlComboBox.setMinimumSize(QtCore.QSize(441, 40))
        self.urlComboBox.setEditable(True)
        self.urlComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.urlComboBox.setObjectName("urlComboBox")
        self.urlComboBox.addItem("")
        self.urlComboBox.addItem("")
        self.gridLayout.addWidget(self.urlComboBox, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.openProjectGroupBox, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setAcceptDrops(False)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionAbout_Textract = QtWidgets.QAction(MainWindow)
        self.actionAbout_Textract.setObjectName("actionAbout_Textract")
        self.action_About_Textract = QtWidgets.QAction(MainWindow)
        self.action_About_Textract.setObjectName("action_About_Textract")
        self.action_About_Author = QtWidgets.QAction(MainWindow)
        self.action_About_Author.setObjectName("action_About_Author")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Keetext"))
        self.outputFormatGroupBox.setTitle(_translate("MainWindow", "Output Format"))
        self.outputComboBox.setItemText(0, _translate("MainWindow", "All in One File"))
        self.outputComboBox.setItemText(1, _translate("MainWindow", "Based on Category"))
        self.outputComboBox.setItemText(2, _translate("MainWindow", "Based on Subcategory"))
        self.starRatingGroupBox.setTitle(_translate("MainWindow", "Select Star Rating"))
        self.fiveStarRadioButton.setText(_translate("MainWindow", "Five Stars"))
        self.twoStarRadioButton.setText(_translate("MainWindow", "Two Stars"))
        self.oneStarRadioButton.setText(_translate("MainWindow", "One Star"))
        self.fourStarRadioButton.setText(_translate("MainWindow", "Four Stars"))
        self.threeStarRadioButton.setText(_translate("MainWindow", "Three Stars"))
        self.productRankGroupBox.setTitle(_translate("MainWindow", "Product Rank"))
        self.minimumRankLabel.setText(_translate("MainWindow", "Minimum"))
        self.maximumRankLabel.setText(_translate("MainWindow", "Maximum"))
        self.productSubrankGroupBox.setTitle(_translate("MainWindow", "Product Sub-rank"))
        self.label_3.setText(_translate("MainWindow", "Minimum"))
        self.label_4.setText(_translate("MainWindow", "Maximum"))
        self.productStatusGroupBox.setTitle(_translate("MainWindow", "Product Status"))
        self.radioButton_7.setText(_translate("MainWindow", "Not Available Product"))
        self.radioButton_6.setText(_translate("MainWindow", "All Available Product"))
        self.outputGroupBox.setTitle(_translate("MainWindow", "Output Directory"))
        __sortingEnabled = self.outputDListWidget.isSortingEnabled()
        self.outputDListWidget.setSortingEnabled(False)
        item = self.outputDListWidget.item(0)
        item.setText(_translate("MainWindow", "Sample Output File 1"))
        self.outputDListWidget.setSortingEnabled(__sortingEnabled)
        self.outputBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.topCategoriesCheckBox.setText(_translate("MainWindow", "Top Categories"))
        self.selectCategoryListWidget.setToolTip(_translate("MainWindow", "Select the Categories of Interest"))
        __sortingEnabled = self.selectCategoryListWidget.isSortingEnabled()
        self.selectCategoryListWidget.setSortingEnabled(False)
        item = self.selectCategoryListWidget.item(0)
        item.setText(_translate("MainWindow", "Sample Category 1"))
        item = self.selectCategoryListWidget.item(1)
        item.setText(_translate("MainWindow", "Sample Category 2"))
        item = self.selectCategoryListWidget.item(2)
        item.setText(_translate("MainWindow", "Sample Category 3"))
        item = self.selectCategoryListWidget.item(3)
        item.setText(_translate("MainWindow", "Sample Category 4"))
        item = self.selectCategoryListWidget.item(4)
        item.setText(_translate("MainWindow", "Sample Category 5"))
        self.selectCategoryListWidget.setSortingEnabled(__sortingEnabled)
        self.selectSubcategoryCheckBox.setText(_translate("MainWindow", "Select Subcategory"))
        __sortingEnabled = self.selectSubcategoryListWidget.isSortingEnabled()
        self.selectSubcategoryListWidget.setSortingEnabled(False)
        item = self.selectSubcategoryListWidget.item(0)
        item.setText(_translate("MainWindow", "Sample Subcategory 1"))
        item = self.selectSubcategoryListWidget.item(1)
        item.setText(_translate("MainWindow", "Sample Subcategory 2"))
        item = self.selectSubcategoryListWidget.item(2)
        item.setText(_translate("MainWindow", "Sample Subcategory 3"))
        self.selectSubcategoryListWidget.setSortingEnabled(__sortingEnabled)
        self.openProjectGroupBox.setTitle(_translate("MainWindow", "Choose Amazon Domain"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.urlComboBox.setToolTip(_translate("MainWindow", "the feature for changing various Amazon Domains is Coming Soon!"))
        self.urlComboBox.setItemText(0, _translate("MainWindow", "https://www.amazon.de"))
        self.urlComboBox.setItemText(1, _translate("MainWindow", "https://www.amazon.com"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.actionAbout_Textract.setText(_translate("MainWindow", "About Textract"))
        self.action_About_Textract.setText(_translate("MainWindow", "&About Textract"))
        self.action_About_Author.setText(_translate("MainWindow", "&About Author"))

import ui.base_rc
